### ISSUE TITLE
Security Upgrades

### ISSUE THREAD

**Issue by UTXOnly** [UTXOnly/nost-py#11]
Special thanks to @maths on my [StackerNews post](https://stacker.news/items/216215/r/NabismoPrime) for the code review, where they made the following observations:

## Issues
**Shell Injection**: The script uses the `os.system()` and `subprocess` methods with string formatting to execute shell commands. This makes the script vulnerable to shell injection attacks, especially if user-supplied input is used. For instance, if an attacker can influence the `default_conf` or `domain_name` values, they could potentially execute arbitrary commands.

**Sensitive Data Exposure**: The script prints out the `script_user`, which could potentially reveal sensitive information about the system. Furthermore, it is handling environment variables that likely contain sensitive information.

**Arbitrary File Deletion**: The script deletes files using the `rm -rf` command, which is a dangerous operation that can delete directories and their contents recursively. In this case, the `default_conf` file is deleted. If an attacker can control the path, this could lead to deletion of any file or directory.

**Insecure File Permissions**: The script modifies the file permissions of certain files using the `chmod` command. This could potentially lead to inappropriate access to sensitive files.

**Unchecked Return Values**: The script does not check the return values of the system or subprocess calls, which can lead to unnoticed failures. If these calls fail, the script continues to execute, which can lead to unexpected behavior.

**Insecure Temporary File**: The script writes the `nginx_config` to a file, but it does not check if the file already exists. An attacker could potentially create a symlink to another file, and the script would overwrite that file instead.

## Steps to resolve

**To mitigate these issues:**

Replace lines with `os.system()` and `subprocess` with string formatting. Instead, use `subprocess.run()` with a list of arguments.
Check the return values of system or subprocess calls and handle errors appropriately.

**Comment by PastaGringo** [comment]
Waiting update so 👍
